name: Point Incrementer

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, closed, reopened, assigned, unassigned]

jobs:
  approval_incrementer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: github object
        if: github.event_name == 'pull_request_review'
        run: |
          curl -d 'pointed_event[value]=1000&pointed_event[type]=PR_APPROVAL&pointed_event[user]=${{github.event.review.user.login}}' https://colaborank.herokuapp.com/api/v1/pointed_events.json

